"""Update ProductMovement model

Revision ID: ccb6db8d021c
Revises: 
Create Date: 2025-08-09 20:30:47.851049

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers
revision = 'ccb6db8d021c'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # 1. Add new columns
    with op.batch_alter_table('product_movement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_location_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('to_location_id', sa.String(length=50), nullable=True))

    # 2. Copy data from old columns to new columns
    op.execute("""
        UPDATE product_movement
        SET from_location_id = from_location,
            to_location_id = to_location
    """)

    # 3. Drop old columns
    with op.batch_alter_table('product_movement', schema=None) as batch_op:
        batch_op.drop_column('from_location')
        batch_op.drop_column('to_location')

    # 4. Add new foreign keys
    with op.batch_alter_table('product_movement', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_product_movement_from_location_id',
            'location',
            ['from_location_id'],
            ['location_id']
        )
        batch_op.create_foreign_key(
            'fk_product_movement_to_location_id',
            'location',
            ['to_location_id'],
            ['location_id']
        )
        
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_movement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('to_location', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('from_location', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'location', ['from_location'], ['location_id'])
        batch_op.create_foreign_key(None, 'location', ['to_location'], ['location_id'])
        batch_op.drop_column('to_location_id')
        batch_op.drop_column('from_location_id')

    # ### end Alembic commands ###
